theme: jekyll-theme-cayman
title: Basim's Website
description: An example on how to use Github pages
github:
  page2: aboutgermany.html
  page3: page3.html
  page4: javascript.html
  page5: famous.html
