theme: jekyll-theme-cayman
title: Basim's Website
description: An example on how to use Github pages
github:
  page2: aboutgermany.html
  page3: germanvocabularly.html
  page4: famouspeople.html
  page5: furtherstudy.html
