theme: jekyll-theme-cayman
title: Basim's Website
description: A Guide to German Language
github:
  page2: aboutgermany.html
  page3: germanvocabularly.html
  page4: germanphrases.html
  page5: famouspeople.html
  page6: furtherstudy.html
